### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bugsysiegals** [jordanjambazov/jira-timesheet-pdf#1]
I've cloned your repo with "git clone" and your https address but am lost with the next command.  I typed docker into git-bash which doesn't work.  I changed to jira-timesheet-pdf directory and it didn't work there either.  Please advise.

**Comment by jordanjambazov** [comment]
@bugsysiegals Please refer to the docker installation manual: https://docs.docker.com/toolbox/toolbox_install_windows/
