### ISSUE TITLE
Remove "Force HTTPS"

### ISSUE THREAD

**Issue by nicolastarzia** [jordanjambazov/jira-timesheet-pdf#7]
Hi,
Can I remove the force of HTTPS URL?
I have a hosted JIRA without HTTPS url.

https://github.com/jordanjambazov/jira-timesheet-pdf/blob/74f43b10799ad74347b06507aeedd6a19d9cfc3c/src/main.py#L60

**Comment by jordanjambazov** [comment]
Sure, feel free to adjust for your needs.
